services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: pickleball_db
      POSTGRES_USER: pickleuser
      POSTGRES_PASSWORD: picklepass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

  admin_panel:
    build:
      context: ./admin_panel
    command: python manage.py runserver 0.0.0.0:8001
    volumes:
      - ./admin_panel:/app
    ports:
      - "8001:8001"
    depends_on:
      - db
    environment:
      - DJANGO_SUPERUSER_USERNAME=admin
      - DJANGO_SUPERUSER_PASSWORD=admin
      - DJANGO_SUPERUSER_EMAIL=admin@example.com
      - DATABASE_URL=postgres://pickleuser:picklepass@db:5432/pickleball_db

volumes:
  postgres_data:


