name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        export_default_credentials: true

    - name: Build and push FastAPI service 1
      run: |
        gcloud builds submit ./fastapi_service_1 \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi1

    - name: Deploy FastAPI service 1 to Cloud Run
      run: |
        gcloud run deploy fastapi1 \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/fastapi1 \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated


    - name: Build and push Django Admin
      run: |
        gcloud builds submit ./admin_panel \
          --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-admin

    - name: Deploy Django Admin to Cloud Run
      run: |
        gcloud run deploy django-admin \
          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/django-admin \
          --platform managed \
          --region ${{ secrets.GCP_REGION }} \
          --allow-unauthenticated
